Fix lib being undefined
error: undefined variable 'lib'

       at /nix/store/11h0kd8pnjimk4a0cpg1in6nmipbniby-source/flake.nix:44:71:

           43|                 mkdir -p "$out"
           44|                 substitute "$src" "$out/bash-env.nu" --replace-fail ${lib.escapeShellArg "bash-env-json"} ${lib.escapeShellArg "${flakePkgs.bash-env-json}/bin/bash-env-json"}
             |                                                                       ^
           45|                 runHook postBuild

Also removed unused readFile.